#!/bin/bash
export MAKEFILE_TEST_ROOT=$(pwd)
export MAKEFILE_TEST_INSTALL=$MAKEFILE_TEST_ROOT/bin
export MAKEFILE_TEST_INCLUDE=$MAKEFILE_TEST_ROOT/include
export MAKEFILE_TEST_LIB=$MAKEFILE_TEST_ROOT/lib
export MAKEFILE_TEST_SRC=$MAKEFILE_TEST_ROOT/src
export MAKEFILE_TEST_TEST=$MAKEFILE_TEST_ROOT/test

# RELEASE or DEBUG
export MAKEFILE_TEST_BUILD_TARGET=DEBUG

